/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck
export interface $DbEnums {
  RoleLevel: 'System' | 'Organization' | 'Project';
  EndpointType: 'GRAPHQL' | 'REST_API';
  BillingStatus: 'free' | 'early_adopter' | 'active' | 'past_due' | 'cancelled';
  BillingInterval: 'monthly' | 'yearly';
}
