/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck
import * as $runtime from '@prisma/client/runtime/client';

/**
 * @param organizationId
 */
export const countOrgRowVersions = $runtime.makeTypedQueryFactory(
  '\nSELECT COUNT(DISTINCT r."versionId") AS "count"\nFROM "Row" r\nJOIN "_RowToTable" rt ON rt."A" = r."versionId"\nJOIN "Table" t ON t."versionId" = rt."B"\nJOIN "_RevisionToTable" rvt ON rvt."B" = t."versionId"\nJOIN "Revision" rv ON rv."id" = rvt."A"\nJOIN "Branch" b ON b."id" = rv."branchId"\nJOIN "Project" p ON p."id" = b."projectId"\nWHERE p."organizationId" = $1\nAND p."isDeleted" = false',
) as (
  organizationId: string,
) => $runtime.TypedSql<
  countOrgRowVersions.Parameters,
  countOrgRowVersions.Result
>;

export namespace countOrgRowVersions {
  export type Parameters = [organizationId: string];
  export type Result = {
    count: bigint | null;
  };
}
