
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
import * as $runtime from "@prisma/client/runtime/client"

/**
 * @param fromRevisionId The id of the revision
 * @param toRevisionId The id of the revision
 */
export const countTableDiffsBetweenRevisions = $runtime.makeTypedQueryFactory("\nWITH parent_tables AS (SELECT \"id\", \"createdId\", \"versionId\"\nFROM \"Table\"\nWHERE (\"public\".\"Table\".\"versionId\") IN (SELECT \"t1\".\"B\"\nFROM \"public\".\"_RevisionToTable\" AS \"t1\"\nINNER JOIN \"public\".\"Revision\" AS \"j1\" ON (\"j1\".\"id\") = (\"t1\".\"A\")\nWHERE (\"j1\".\"id\" = $1 AND \"t1\".\"B\" IS NOT NULL))),\nchild_tables AS (SELECT \"id\", \"createdId\", \"versionId\"\nFROM \"Table\"\nWHERE (\"public\".\"Table\".\"versionId\") IN (SELECT \"t1\".\"B\"\nFROM \"public\".\"_RevisionToTable\" AS \"t1\"\nINNER JOIN \"public\".\"Revision\" AS \"j1\" ON (\"j1\".\"id\") = (\"t1\".\"A\")\nWHERE (\"j1\".\"id\" = $2 AND \"t1\".\"B\" IS NOT NULL)))\nSELECT COUNT(*) ::integer AS count\nFROM\nchild_tables ct\nFULL OUTER JOIN parent_tables pt USING (\"createdId\")\nWHERE\npt.\"createdId\" IS NULL\nOR\nct.\"createdId\" IS NULL\nOR\nct.\"versionId\" != pt.\"versionId\"\n") as (fromRevisionId: string, toRevisionId: string) => $runtime.TypedSql<countTableDiffsBetweenRevisions.Parameters, countTableDiffsBetweenRevisions.Result>

export namespace countTableDiffsBetweenRevisions {
  export type Parameters = [fromRevisionId: string, toRevisionId: string]
  export type Result = {
    count: number | null
  }
}
