
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
import * as $runtime from "@prisma/client/runtime/client"

/**
 * @param fromRevisionId The id of the revision
 * @param toRevisionId The id of the revision
 * @param includeSystem Whether to include system tables (default false)
 */
export const countTableDiffsBetweenRevisions = $runtime.makeTypedQueryFactory("\nWITH parent_tables AS (SELECT \"id\", \"createdId\", \"versionId\"\nFROM \"Table\"\nWHERE (\"Table\".\"versionId\") IN (SELECT \"t1\".\"B\"\nFROM \"_RevisionToTable\" AS \"t1\"\nINNER JOIN \"Revision\" AS \"j1\" ON (\"j1\".\"id\") = (\"t1\".\"A\")\nWHERE (\"j1\".\"id\" = $1 AND \"t1\".\"B\" IS NOT NULL))\nAND ($3::boolean IS TRUE OR \"Table\".\"system\" = FALSE)),\nchild_tables AS (SELECT \"id\", \"createdId\", \"versionId\"\nFROM \"Table\"\nWHERE (\"Table\".\"versionId\") IN (SELECT \"t1\".\"B\"\nFROM \"_RevisionToTable\" AS \"t1\"\nINNER JOIN \"Revision\" AS \"j1\" ON (\"j1\".\"id\") = (\"t1\".\"A\")\nWHERE (\"j1\".\"id\" = $2 AND \"t1\".\"B\" IS NOT NULL))\nAND ($3::boolean IS TRUE OR \"Table\".\"system\" = FALSE))\nSELECT COUNT(*) ::integer AS count\nFROM\nchild_tables ct\nFULL OUTER JOIN parent_tables pt USING (\"createdId\")\nWHERE\npt.\"createdId\" IS NULL\nOR\nct.\"createdId\" IS NULL\nOR\npt.\"id\" != ct.\"id\"\nOR\nct.\"versionId\" != pt.\"versionId\"\n") as (fromRevisionId: string, toRevisionId: string, includeSystem: boolean) => $runtime.TypedSql<countTableDiffsBetweenRevisions.Parameters, countTableDiffsBetweenRevisions.Result>

export namespace countTableDiffsBetweenRevisions {
  export type Parameters = [fromRevisionId: string, toRevisionId: string, includeSystem: boolean]
  export type Result = {
    count: number | null
  }
}
