
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
import * as $runtime from "@prisma/client/runtime/client"

/**
 * @param fromRevisionId The id of the revision
 * @param toRevisionId The id of the revision
 * @param limit
 * @param offset
 * @param includeSystem Whether to include system tables (default false)
 */
export const getTableDiffsPaginatedBetweenRevisions = $runtime.makeTypedQueryFactory("\nWITH parent_tables AS (SELECT \"id\", \"createdId\", \"versionId\"\nFROM \"Table\"\nWHERE (\"Table\".\"versionId\") IN (SELECT \"t1\".\"B\"\nFROM \"_RevisionToTable\" AS \"t1\"\nINNER JOIN \"Revision\" AS \"j1\" ON (\"j1\".\"id\") = (\"t1\".\"A\")\nWHERE (\"j1\".\"id\" = $1 AND \"t1\".\"B\" IS NOT NULL))\nAND ($5::boolean IS TRUE OR \"Table\".\"system\" = FALSE)),\nchild_tables AS (SELECT \"id\", \"createdId\", \"versionId\"\nFROM \"Table\"\nWHERE (\"Table\".\"versionId\") IN (SELECT \"t1\".\"B\"\nFROM \"_RevisionToTable\" AS \"t1\"\nINNER JOIN \"Revision\" AS \"j1\" ON (\"j1\".\"id\") = (\"t1\".\"A\")\nWHERE (\"j1\".\"id\" = $2 AND \"t1\".\"B\" IS NOT NULL))\nAND ($5::boolean IS TRUE OR \"Table\".\"system\" = FALSE))\nSELECT pt.\"id\"        AS \"fromId\",\npt.\"createdId\" AS \"fromCreatedId\",\npt.\"versionId\" AS \"fromVersionId\",\nct.\"id\"        AS \"toId\",\nct.\"createdId\" AS \"toCreatedId\",\nct.\"versionId\" AS \"toVersionId\",\nCASE\nWHEN pt.\"createdId\" IS NULL THEN 'added'\nWHEN ct.\"createdId\" IS NULL THEN 'removed'\nWHEN pt.\"id\" != ct.\"id\" THEN 'renamed'\nWHEN ct.\"versionId\" != pt.\"versionId\" THEN 'modified'\nEND        AS \"changeType\"\nFROM child_tables ct\nFULL OUTER JOIN parent_tables pt USING (\"createdId\")\nWHERE pt.\"createdId\" IS NULL\nOR ct.\"createdId\" IS NULL\nOR pt.\"id\" != ct.\"id\"\nOR ct.\"versionId\" != pt.\"versionId\"\n\nLIMIT $3\nOFFSET $4\n") as (fromRevisionId: string, toRevisionId: string, limit: number, offset: number, includeSystem: boolean) => $runtime.TypedSql<getTableDiffsPaginatedBetweenRevisions.Parameters, getTableDiffsPaginatedBetweenRevisions.Result>

export namespace getTableDiffsPaginatedBetweenRevisions {
  export type Parameters = [fromRevisionId: string, toRevisionId: string, limit: number, offset: number, includeSystem: boolean]
  export type Result = {
    fromId: string
    fromCreatedId: string
    fromVersionId: string
    toId: string
    toCreatedId: string
    toVersionId: string
    changeType: string | null
  }
}
