/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck
/*
 * This file exports all enum related types from the schema.
 *
 * 🟢 You can import this file directly.
 */

export const RoleLevel = {
  System: 'System',
  Organization: 'Organization',
  Project: 'Project',
} as const;

export type RoleLevel = (typeof RoleLevel)[keyof typeof RoleLevel];

export const EndpointType = {
  GRAPHQL: 'GRAPHQL',
  REST_API: 'REST_API',
} as const;

export type EndpointType = (typeof EndpointType)[keyof typeof EndpointType];

export const BillingStatus = {
  free: 'free',
  early_adopter: 'early_adopter',
  active: 'active',
  past_due: 'past_due',
  cancelled: 'cancelled',
} as const;

export type BillingStatus = (typeof BillingStatus)[keyof typeof BillingStatus];

export const BillingInterval = {
  monthly: 'monthly',
  yearly: 'yearly',
} as const;

export type BillingInterval =
  (typeof BillingInterval)[keyof typeof BillingInterval];
