import { NestFactory } from '@nestjs/core';
import { execSync } from 'child_process';
import * as fs from 'fs';
import * as path from 'path';
import { AppModule } from 'src/app.module';
import { PrismaService } from 'src/infrastructure/database/prisma.service';
import { runAllSeeds } from '../seeds';

const SNAPSHOT_PATH = path.join(__dirname, '..', 'snapshot.sql');

async function generateSnapshot(): Promise<void> {
  console.log('=== Generating Test Fixtures Snapshot ===\n');

  console.log('1. Starting NestJS application...');
  const app = await NestFactory.create(AppModule, { logger: false });
  const prisma = app.get(PrismaService);

  console.log('2. Cleaning fixture data (keeping seed data)...');
  await prisma.$executeRawUnsafe(`
    TRUNCATE TABLE
      "_RowToTable",
      "_RevisionToTable",
      "Row",
      "Table",
      "Endpoint",
      "Revision",
      "Branch",
      "UserProject",
      "Project"
    RESTART IDENTITY CASCADE;

    DELETE FROM "UserOrganization" WHERE id NOT IN (
      SELECT uo.id FROM "UserOrganization" uo
      JOIN "User" u ON uo."userId" = u.id
      WHERE u."roleId" = 'systemAdmin' OR u."roleId" = 'systemFullApiRead'
    );

    DELETE FROM "Organization" WHERE id NOT IN (
      SELECT o.id FROM "Organization" o
      JOIN "UserOrganization" uo ON o.id = uo."organizationId"
      JOIN "User" u ON uo."userId" = u.id
      WHERE u."roleId" = 'systemAdmin' OR u."roleId" = 'systemFullApiRead'
    ) AND id NOT IN ('__system');

    DELETE FROM "User" WHERE "roleId" NOT IN ('systemAdmin', 'systemFullApiRead');
  `);

  console.log('3. Running fixture seeds...');
  await runAllSeeds(app);

  const databaseUrl = process.env.DATABASE_URL;
  if (!databaseUrl) {
    throw new Error('DATABASE_URL is not set');
  }

  console.log('4. Generating SQL dump...');
  const tables = [
    'User',
    'Organization',
    'UserOrganization',
    'Project',
    'UserProject',
    'Branch',
    'Revision',
    'Endpoint',
    'Table',
    'Row',
    '_RevisionToTable',
    '_RowToTable',
  ];

  const tableArgs = tables.map((t) => `-t "\\"${t}\\""`).join(' ');
  const dumpCommand = `pg_dump "${databaseUrl}" --data-only --inserts ${tableArgs}`;

  try {
    const dump = execSync(dumpCommand, { encoding: 'utf-8', maxBuffer: 50 * 1024 * 1024 });

    const header = `-- Test Fixtures Snapshot
-- Generated: ${new Date().toISOString()}
--
-- This file is auto-generated by: npm run fixtures:snapshot
-- Do not edit manually.
--
-- Usage in CI:
--   1. Run seed first: npm run seed
--   2. Load fixtures: psql $DATABASE_URL < src/__tests__/fixtures/snapshot.sql
--

-- Clean existing fixture data before loading
TRUNCATE TABLE
  "_RowToTable",
  "_RevisionToTable",
  "Row",
  "Table",
  "Endpoint",
  "Revision",
  "Branch",
  "UserProject",
  "Project"
RESTART IDENTITY CASCADE;

DELETE FROM "UserOrganization" WHERE id NOT IN (
  SELECT uo.id FROM "UserOrganization" uo
  JOIN "User" u ON uo."userId" = u.id
  WHERE u."roleId" = 'systemAdmin' OR u."roleId" = 'systemFullApiRead'
);

DELETE FROM "Organization" WHERE id NOT IN (
  SELECT o.id FROM "Organization" o
  JOIN "UserOrganization" uo ON o.id = uo."organizationId"
  JOIN "User" u ON uo."userId" = u.id
  WHERE u."roleId" = 'systemAdmin' OR u."roleId" = 'systemFullApiRead'
) AND id NOT IN ('__system');

DELETE FROM "User" WHERE "roleId" NOT IN ('systemAdmin', 'systemFullApiRead');

-- Fixture data starts here

`;
    fs.writeFileSync(SNAPSHOT_PATH, header + dump);
    console.log(`5. Snapshot saved to: ${SNAPSHOT_PATH}`);

    const stats = await getStats(prisma);
    console.log('\nSnapshot stats:');
    console.log(`  Users: ${stats.users}`);
    console.log(`  Organizations: ${stats.organizations}`);
    console.log(`  Projects: ${stats.projects}`);
    console.log(`  Branches: ${stats.branches}`);
    console.log(`  Revisions: ${stats.revisions}`);
    console.log(`  Tables: ${stats.tables}`);
    console.log(`  Rows: ${stats.rows}`);
  } catch (error) {
    console.error('Failed to generate dump:', error);
    throw error;
  }

  await app.close();
  console.log('\n=== Done ===');
}

async function getStats(prisma: PrismaService) {
  return {
    users: await prisma.user.count(),
    organizations: await prisma.organization.count(),
    projects: await prisma.project.count(),
    branches: await prisma.branch.count(),
    revisions: await prisma.revision.count(),
    tables: await prisma.table.count(),
    rows: await prisma.row.count(),
  };
}

generateSnapshot().catch((error) => {
  console.error(error);
  process.exit(1);
});
