
/* !!! This is code generated by Prisma. Do not edit directly. !!!
/* eslint-disable */
"use strict"
exports.countTableDiffsBetweenRevisions = require("./countTableDiffsBetweenRevisions.edge.js").countTableDiffsBetweenRevisions
exports.getTableDiffsPaginatedBetweenRevisions = require("./getTableDiffsPaginatedBetweenRevisions.edge.js").getTableDiffsPaginatedBetweenRevisions
exports.hasRowDiffsBetweenRevisions = require("./hasRowDiffsBetweenRevisions.edge.js").hasRowDiffsBetweenRevisions
exports.hasTableDiffsBetweenRevisions = require("./hasTableDiffsBetweenRevisions.edge.js").hasTableDiffsBetweenRevisions
