
/* !!! This is code generated by Prisma. Do not edit directly. !!!
/* eslint-disable */
export * from "./countTableDiffsBetweenRevisions.mjs"
export * from "./getTableDiffsPaginatedBetweenRevisions.mjs"
export * from "./hasRowDiffsBetweenRevisions.mjs"
export * from "./hasTableDiffsBetweenRevisions.mjs"
