
/* !!! This is code generated by Prisma. Do not edit directly. !!!
/* eslint-disable */
"use strict"
exports.countTableDiffsBetweenRevisions = require("./countTableDiffsBetweenRevisions.js").countTableDiffsBetweenRevisions
exports.getTableDiffsPaginatedBetweenRevisions = require("./getTableDiffsPaginatedBetweenRevisions.js").getTableDiffsPaginatedBetweenRevisions
exports.hasRowDiffsBetweenRevisions = require("./hasRowDiffsBetweenRevisions.js").hasRowDiffsBetweenRevisions
exports.hasTableDiffsBetweenRevisions = require("./hasTableDiffsBetweenRevisions.js").hasTableDiffsBetweenRevisions
