
/* !!! This is code generated by Prisma. Do not edit directly. !!!
/* eslint-disable */
export * from "./countTableDiffsBetweenRevisions.edge.mjs"
export * from "./getTableDiffsPaginatedBetweenRevisions.edge.mjs"
export * from "./hasRowDiffsBetweenRevisions.edge.mjs"
export * from "./hasTableDiffsBetweenRevisions.edge.mjs"
