/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck
/*
 * This file exports the `LicenseCache` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from '@prisma/client/runtime/client';
import type * as $Enums from '../enums';
import type * as Prisma from '../internal/prismaNamespace';

/**
 * Model LicenseCache
 *
 */
export type LicenseCacheModel =
  runtime.Types.Result.DefaultSelection<Prisma.$LicenseCachePayload>;

export type AggregateLicenseCache = {
  _count: LicenseCacheCountAggregateOutputType | null;
  _min: LicenseCacheMinAggregateOutputType | null;
  _max: LicenseCacheMaxAggregateOutputType | null;
};

export type LicenseCacheMinAggregateOutputType = {
  id: string | null;
  validatedAt: Date | null;
  createdAt: Date | null;
  updatedAt: Date | null;
};

export type LicenseCacheMaxAggregateOutputType = {
  id: string | null;
  validatedAt: Date | null;
  createdAt: Date | null;
  updatedAt: Date | null;
};

export type LicenseCacheCountAggregateOutputType = {
  id: number;
  payload: number;
  validatedAt: number;
  createdAt: number;
  updatedAt: number;
  _all: number;
};

export type LicenseCacheMinAggregateInputType = {
  id?: true;
  validatedAt?: true;
  createdAt?: true;
  updatedAt?: true;
};

export type LicenseCacheMaxAggregateInputType = {
  id?: true;
  validatedAt?: true;
  createdAt?: true;
  updatedAt?: true;
};

export type LicenseCacheCountAggregateInputType = {
  id?: true;
  payload?: true;
  validatedAt?: true;
  createdAt?: true;
  updatedAt?: true;
  _all?: true;
};

export type LicenseCacheAggregateArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs =
    runtime.Types.Extensions.DefaultArgs,
> = {
  /**
   * Filter which LicenseCache to aggregate.
   */
  where?: Prisma.LicenseCacheWhereInput;
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   *
   * Determine the order of LicenseCaches to fetch.
   */
  orderBy?:
    | Prisma.LicenseCacheOrderByWithRelationInput
    | Prisma.LicenseCacheOrderByWithRelationInput[];
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   *
   * Sets the start position
   */
  cursor?: Prisma.LicenseCacheWhereUniqueInput;
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   *
   * Take `±n` LicenseCaches from the position of the cursor.
   */
  take?: number;
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   *
   * Skip the first `n` LicenseCaches.
   */
  skip?: number;
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   *
   * Count returned LicenseCaches
   **/
  _count?: true | LicenseCacheCountAggregateInputType;
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   *
   * Select which fields to find the minimum value
   **/
  _min?: LicenseCacheMinAggregateInputType;
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   *
   * Select which fields to find the maximum value
   **/
  _max?: LicenseCacheMaxAggregateInputType;
};

export type GetLicenseCacheAggregateType<T extends LicenseCacheAggregateArgs> =
  {
    [P in keyof T & keyof AggregateLicenseCache]: P extends '_count' | 'count'
      ? T[P] extends true
        ? number
        : Prisma.GetScalarType<T[P], AggregateLicenseCache[P]>
      : Prisma.GetScalarType<T[P], AggregateLicenseCache[P]>;
  };

export type LicenseCacheGroupByArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs =
    runtime.Types.Extensions.DefaultArgs,
> = {
  where?: Prisma.LicenseCacheWhereInput;
  orderBy?:
    | Prisma.LicenseCacheOrderByWithAggregationInput
    | Prisma.LicenseCacheOrderByWithAggregationInput[];
  by: Prisma.LicenseCacheScalarFieldEnum[] | Prisma.LicenseCacheScalarFieldEnum;
  having?: Prisma.LicenseCacheScalarWhereWithAggregatesInput;
  take?: number;
  skip?: number;
  _count?: LicenseCacheCountAggregateInputType | true;
  _min?: LicenseCacheMinAggregateInputType;
  _max?: LicenseCacheMaxAggregateInputType;
};

export type LicenseCacheGroupByOutputType = {
  id: string;
  payload: runtime.JsonValue;
  validatedAt: Date;
  createdAt: Date;
  updatedAt: Date;
  _count: LicenseCacheCountAggregateOutputType | null;
  _min: LicenseCacheMinAggregateOutputType | null;
  _max: LicenseCacheMaxAggregateOutputType | null;
};

type GetLicenseCacheGroupByPayload<T extends LicenseCacheGroupByArgs> =
  Prisma.PrismaPromise<
    Array<
      Prisma.PickEnumerable<LicenseCacheGroupByOutputType, T['by']> & {
        [P in keyof T & keyof LicenseCacheGroupByOutputType]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], LicenseCacheGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], LicenseCacheGroupByOutputType[P]>;
      }
    >
  >;

export type LicenseCacheWhereInput = {
  AND?: Prisma.LicenseCacheWhereInput | Prisma.LicenseCacheWhereInput[];
  OR?: Prisma.LicenseCacheWhereInput[];
  NOT?: Prisma.LicenseCacheWhereInput | Prisma.LicenseCacheWhereInput[];
  id?: Prisma.StringFilter<'LicenseCache'> | string;
  payload?: Prisma.JsonFilter<'LicenseCache'>;
  validatedAt?: Prisma.DateTimeFilter<'LicenseCache'> | Date | string;
  createdAt?: Prisma.DateTimeFilter<'LicenseCache'> | Date | string;
  updatedAt?: Prisma.DateTimeFilter<'LicenseCache'> | Date | string;
};

export type LicenseCacheOrderByWithRelationInput = {
  id?: Prisma.SortOrder;
  payload?: Prisma.SortOrder;
  validatedAt?: Prisma.SortOrder;
  createdAt?: Prisma.SortOrder;
  updatedAt?: Prisma.SortOrder;
  _relevance?: Prisma.LicenseCacheOrderByRelevanceInput;
};

export type LicenseCacheWhereUniqueInput = Prisma.AtLeast<
  {
    id?: string;
    AND?: Prisma.LicenseCacheWhereInput | Prisma.LicenseCacheWhereInput[];
    OR?: Prisma.LicenseCacheWhereInput[];
    NOT?: Prisma.LicenseCacheWhereInput | Prisma.LicenseCacheWhereInput[];
    payload?: Prisma.JsonFilter<'LicenseCache'>;
    validatedAt?: Prisma.DateTimeFilter<'LicenseCache'> | Date | string;
    createdAt?: Prisma.DateTimeFilter<'LicenseCache'> | Date | string;
    updatedAt?: Prisma.DateTimeFilter<'LicenseCache'> | Date | string;
  },
  'id'
>;

export type LicenseCacheOrderByWithAggregationInput = {
  id?: Prisma.SortOrder;
  payload?: Prisma.SortOrder;
  validatedAt?: Prisma.SortOrder;
  createdAt?: Prisma.SortOrder;
  updatedAt?: Prisma.SortOrder;
  _count?: Prisma.LicenseCacheCountOrderByAggregateInput;
  _max?: Prisma.LicenseCacheMaxOrderByAggregateInput;
  _min?: Prisma.LicenseCacheMinOrderByAggregateInput;
};

export type LicenseCacheScalarWhereWithAggregatesInput = {
  AND?:
    | Prisma.LicenseCacheScalarWhereWithAggregatesInput
    | Prisma.LicenseCacheScalarWhereWithAggregatesInput[];
  OR?: Prisma.LicenseCacheScalarWhereWithAggregatesInput[];
  NOT?:
    | Prisma.LicenseCacheScalarWhereWithAggregatesInput
    | Prisma.LicenseCacheScalarWhereWithAggregatesInput[];
  id?: Prisma.StringWithAggregatesFilter<'LicenseCache'> | string;
  payload?: Prisma.JsonWithAggregatesFilter<'LicenseCache'>;
  validatedAt?:
    | Prisma.DateTimeWithAggregatesFilter<'LicenseCache'>
    | Date
    | string;
  createdAt?:
    | Prisma.DateTimeWithAggregatesFilter<'LicenseCache'>
    | Date
    | string;
  updatedAt?:
    | Prisma.DateTimeWithAggregatesFilter<'LicenseCache'>
    | Date
    | string;
};

export type LicenseCacheCreateInput = {
  id?: string;
  payload: Prisma.JsonNullValueInput | runtime.InputJsonValue;
  validatedAt: Date | string;
  createdAt?: Date | string;
  updatedAt?: Date | string;
};

export type LicenseCacheUncheckedCreateInput = {
  id?: string;
  payload: Prisma.JsonNullValueInput | runtime.InputJsonValue;
  validatedAt: Date | string;
  createdAt?: Date | string;
  updatedAt?: Date | string;
};

export type LicenseCacheUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string;
  payload?: Prisma.JsonNullValueInput | runtime.InputJsonValue;
  validatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string;
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string;
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string;
};

export type LicenseCacheUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string;
  payload?: Prisma.JsonNullValueInput | runtime.InputJsonValue;
  validatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string;
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string;
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string;
};

export type LicenseCacheCreateManyInput = {
  id?: string;
  payload: Prisma.JsonNullValueInput | runtime.InputJsonValue;
  validatedAt: Date | string;
  createdAt?: Date | string;
  updatedAt?: Date | string;
};

export type LicenseCacheUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string;
  payload?: Prisma.JsonNullValueInput | runtime.InputJsonValue;
  validatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string;
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string;
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string;
};

export type LicenseCacheUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string;
  payload?: Prisma.JsonNullValueInput | runtime.InputJsonValue;
  validatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string;
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string;
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string;
};

export type LicenseCacheOrderByRelevanceInput = {
  fields:
    | Prisma.LicenseCacheOrderByRelevanceFieldEnum
    | Prisma.LicenseCacheOrderByRelevanceFieldEnum[];
  sort: Prisma.SortOrder;
  search: string;
};

export type LicenseCacheCountOrderByAggregateInput = {
  id?: Prisma.SortOrder;
  payload?: Prisma.SortOrder;
  validatedAt?: Prisma.SortOrder;
  createdAt?: Prisma.SortOrder;
  updatedAt?: Prisma.SortOrder;
};

export type LicenseCacheMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder;
  validatedAt?: Prisma.SortOrder;
  createdAt?: Prisma.SortOrder;
  updatedAt?: Prisma.SortOrder;
};

export type LicenseCacheMinOrderByAggregateInput = {
  id?: Prisma.SortOrder;
  validatedAt?: Prisma.SortOrder;
  createdAt?: Prisma.SortOrder;
  updatedAt?: Prisma.SortOrder;
};

export type LicenseCacheSelect<
  ExtArgs extends runtime.Types.Extensions.InternalArgs =
    runtime.Types.Extensions.DefaultArgs,
> = runtime.Types.Extensions.GetSelect<
  {
    id?: boolean;
    payload?: boolean;
    validatedAt?: boolean;
    createdAt?: boolean;
    updatedAt?: boolean;
  },
  ExtArgs['result']['licenseCache']
>;

export type LicenseCacheSelectCreateManyAndReturn<
  ExtArgs extends runtime.Types.Extensions.InternalArgs =
    runtime.Types.Extensions.DefaultArgs,
> = runtime.Types.Extensions.GetSelect<
  {
    id?: boolean;
    payload?: boolean;
    validatedAt?: boolean;
    createdAt?: boolean;
    updatedAt?: boolean;
  },
  ExtArgs['result']['licenseCache']
>;

export type LicenseCacheSelectUpdateManyAndReturn<
  ExtArgs extends runtime.Types.Extensions.InternalArgs =
    runtime.Types.Extensions.DefaultArgs,
> = runtime.Types.Extensions.GetSelect<
  {
    id?: boolean;
    payload?: boolean;
    validatedAt?: boolean;
    createdAt?: boolean;
    updatedAt?: boolean;
  },
  ExtArgs['result']['licenseCache']
>;

export type LicenseCacheSelectScalar = {
  id?: boolean;
  payload?: boolean;
  validatedAt?: boolean;
  createdAt?: boolean;
  updatedAt?: boolean;
};

export type LicenseCacheOmit<
  ExtArgs extends runtime.Types.Extensions.InternalArgs =
    runtime.Types.Extensions.DefaultArgs,
> = runtime.Types.Extensions.GetOmit<
  'id' | 'payload' | 'validatedAt' | 'createdAt' | 'updatedAt',
  ExtArgs['result']['licenseCache']
>;

export type $LicenseCachePayload<
  ExtArgs extends runtime.Types.Extensions.InternalArgs =
    runtime.Types.Extensions.DefaultArgs,
> = {
  name: 'LicenseCache';
  objects: {};
  scalars: runtime.Types.Extensions.GetPayloadResult<
    {
      id: string;
      payload: runtime.JsonValue;
      validatedAt: Date;
      createdAt: Date;
      updatedAt: Date;
    },
    ExtArgs['result']['licenseCache']
  >;
  composites: {};
};

export type LicenseCacheGetPayload<
  S extends boolean | null | undefined | LicenseCacheDefaultArgs,
> = runtime.Types.Result.GetResult<Prisma.$LicenseCachePayload, S>;

export type LicenseCacheCountArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs =
    runtime.Types.Extensions.DefaultArgs,
> = Omit<
  LicenseCacheFindManyArgs,
  'select' | 'include' | 'distinct' | 'omit'
> & {
  select?: LicenseCacheCountAggregateInputType | true;
};

export interface LicenseCacheDelegate<
  ExtArgs extends runtime.Types.Extensions.InternalArgs =
    runtime.Types.Extensions.DefaultArgs,
  GlobalOmitOptions = {},
> {
  [K: symbol]: {
    types: Prisma.TypeMap<ExtArgs>['model']['LicenseCache'];
    meta: { name: 'LicenseCache' };
  };
  /**
   * Find zero or one LicenseCache that matches the filter.
   * @param {LicenseCacheFindUniqueArgs} args - Arguments to find a LicenseCache
   * @example
   * // Get one LicenseCache
   * const licenseCache = await prisma.licenseCache.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends LicenseCacheFindUniqueArgs>(
    args: Prisma.SelectSubset<T, LicenseCacheFindUniqueArgs<ExtArgs>>,
  ): Prisma.Prisma__LicenseCacheClient<
    runtime.Types.Result.GetResult<
      Prisma.$LicenseCachePayload<ExtArgs>,
      T,
      'findUnique',
      GlobalOmitOptions
    > | null,
    null,
    ExtArgs,
    GlobalOmitOptions
  >;

  /**
   * Find one LicenseCache that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {LicenseCacheFindUniqueOrThrowArgs} args - Arguments to find a LicenseCache
   * @example
   * // Get one LicenseCache
   * const licenseCache = await prisma.licenseCache.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends LicenseCacheFindUniqueOrThrowArgs>(
    args: Prisma.SelectSubset<T, LicenseCacheFindUniqueOrThrowArgs<ExtArgs>>,
  ): Prisma.Prisma__LicenseCacheClient<
    runtime.Types.Result.GetResult<
      Prisma.$LicenseCachePayload<ExtArgs>,
      T,
      'findUniqueOrThrow',
      GlobalOmitOptions
    >,
    never,
    ExtArgs,
    GlobalOmitOptions
  >;

  /**
   * Find the first LicenseCache that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {LicenseCacheFindFirstArgs} args - Arguments to find a LicenseCache
   * @example
   * // Get one LicenseCache
   * const licenseCache = await prisma.licenseCache.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends LicenseCacheFindFirstArgs>(
    args?: Prisma.SelectSubset<T, LicenseCacheFindFirstArgs<ExtArgs>>,
  ): Prisma.Prisma__LicenseCacheClient<
    runtime.Types.Result.GetResult<
      Prisma.$LicenseCachePayload<ExtArgs>,
      T,
      'findFirst',
      GlobalOmitOptions
    > | null,
    null,
    ExtArgs,
    GlobalOmitOptions
  >;

  /**
   * Find the first LicenseCache that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {LicenseCacheFindFirstOrThrowArgs} args - Arguments to find a LicenseCache
   * @example
   * // Get one LicenseCache
   * const licenseCache = await prisma.licenseCache.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends LicenseCacheFindFirstOrThrowArgs>(
    args?: Prisma.SelectSubset<T, LicenseCacheFindFirstOrThrowArgs<ExtArgs>>,
  ): Prisma.Prisma__LicenseCacheClient<
    runtime.Types.Result.GetResult<
      Prisma.$LicenseCachePayload<ExtArgs>,
      T,
      'findFirstOrThrow',
      GlobalOmitOptions
    >,
    never,
    ExtArgs,
    GlobalOmitOptions
  >;

  /**
   * Find zero or more LicenseCaches that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {LicenseCacheFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all LicenseCaches
   * const licenseCaches = await prisma.licenseCache.findMany()
   *
   * // Get first 10 LicenseCaches
   * const licenseCaches = await prisma.licenseCache.findMany({ take: 10 })
   *
   * // Only select the `id`
   * const licenseCacheWithIdOnly = await prisma.licenseCache.findMany({ select: { id: true } })
   *
   */
  findMany<T extends LicenseCacheFindManyArgs>(
    args?: Prisma.SelectSubset<T, LicenseCacheFindManyArgs<ExtArgs>>,
  ): Prisma.PrismaPromise<
    runtime.Types.Result.GetResult<
      Prisma.$LicenseCachePayload<ExtArgs>,
      T,
      'findMany',
      GlobalOmitOptions
    >
  >;

  /**
   * Create a LicenseCache.
   * @param {LicenseCacheCreateArgs} args - Arguments to create a LicenseCache.
   * @example
   * // Create one LicenseCache
   * const LicenseCache = await prisma.licenseCache.create({
   *   data: {
   *     // ... data to create a LicenseCache
   *   }
   * })
   *
   */
  create<T extends LicenseCacheCreateArgs>(
    args: Prisma.SelectSubset<T, LicenseCacheCreateArgs<ExtArgs>>,
  ): Prisma.Prisma__LicenseCacheClient<
    runtime.Types.Result.GetResult<
      Prisma.$LicenseCachePayload<ExtArgs>,
      T,
      'create',
      GlobalOmitOptions
    >,
    never,
    ExtArgs,
    GlobalOmitOptions
  >;

  /**
   * Create many LicenseCaches.
   * @param {LicenseCacheCreateManyArgs} args - Arguments to create many LicenseCaches.
   * @example
   * // Create many LicenseCaches
   * const licenseCache = await prisma.licenseCache.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *
   */
  createMany<T extends LicenseCacheCreateManyArgs>(
    args?: Prisma.SelectSubset<T, LicenseCacheCreateManyArgs<ExtArgs>>,
  ): Prisma.PrismaPromise<Prisma.BatchPayload>;

  /**
   * Create many LicenseCaches and returns the data saved in the database.
   * @param {LicenseCacheCreateManyAndReturnArgs} args - Arguments to create many LicenseCaches.
   * @example
   * // Create many LicenseCaches
   * const licenseCache = await prisma.licenseCache.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *
   * // Create many LicenseCaches and only return the `id`
   * const licenseCacheWithIdOnly = await prisma.licenseCache.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   *
   */
  createManyAndReturn<T extends LicenseCacheCreateManyAndReturnArgs>(
    args?: Prisma.SelectSubset<T, LicenseCacheCreateManyAndReturnArgs<ExtArgs>>,
  ): Prisma.PrismaPromise<
    runtime.Types.Result.GetResult<
      Prisma.$LicenseCachePayload<ExtArgs>,
      T,
      'createManyAndReturn',
      GlobalOmitOptions
    >
  >;

  /**
   * Delete a LicenseCache.
   * @param {LicenseCacheDeleteArgs} args - Arguments to delete one LicenseCache.
   * @example
   * // Delete one LicenseCache
   * const LicenseCache = await prisma.licenseCache.delete({
   *   where: {
   *     // ... filter to delete one LicenseCache
   *   }
   * })
   *
   */
  delete<T extends LicenseCacheDeleteArgs>(
    args: Prisma.SelectSubset<T, LicenseCacheDeleteArgs<ExtArgs>>,
  ): Prisma.Prisma__LicenseCacheClient<
    runtime.Types.Result.GetResult<
      Prisma.$LicenseCachePayload<ExtArgs>,
      T,
      'delete',
      GlobalOmitOptions
    >,
    never,
    ExtArgs,
    GlobalOmitOptions
  >;

  /**
   * Update one LicenseCache.
   * @param {LicenseCacheUpdateArgs} args - Arguments to update one LicenseCache.
   * @example
   * // Update one LicenseCache
   * const licenseCache = await prisma.licenseCache.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   *
   */
  update<T extends LicenseCacheUpdateArgs>(
    args: Prisma.SelectSubset<T, LicenseCacheUpdateArgs<ExtArgs>>,
  ): Prisma.Prisma__LicenseCacheClient<
    runtime.Types.Result.GetResult<
      Prisma.$LicenseCachePayload<ExtArgs>,
      T,
      'update',
      GlobalOmitOptions
    >,
    never,
    ExtArgs,
    GlobalOmitOptions
  >;

  /**
   * Delete zero or more LicenseCaches.
   * @param {LicenseCacheDeleteManyArgs} args - Arguments to filter LicenseCaches to delete.
   * @example
   * // Delete a few LicenseCaches
   * const { count } = await prisma.licenseCache.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   *
   */
  deleteMany<T extends LicenseCacheDeleteManyArgs>(
    args?: Prisma.SelectSubset<T, LicenseCacheDeleteManyArgs<ExtArgs>>,
  ): Prisma.PrismaPromise<Prisma.BatchPayload>;

  /**
   * Update zero or more LicenseCaches.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {LicenseCacheUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many LicenseCaches
   * const licenseCache = await prisma.licenseCache.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   *
   */
  updateMany<T extends LicenseCacheUpdateManyArgs>(
    args: Prisma.SelectSubset<T, LicenseCacheUpdateManyArgs<ExtArgs>>,
  ): Prisma.PrismaPromise<Prisma.BatchPayload>;

  /**
   * Update zero or more LicenseCaches and returns the data updated in the database.
   * @param {LicenseCacheUpdateManyAndReturnArgs} args - Arguments to update many LicenseCaches.
   * @example
   * // Update many LicenseCaches
   * const licenseCache = await prisma.licenseCache.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *
   * // Update zero or more LicenseCaches and only return the `id`
   * const licenseCacheWithIdOnly = await prisma.licenseCache.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   *
   */
  updateManyAndReturn<T extends LicenseCacheUpdateManyAndReturnArgs>(
    args: Prisma.SelectSubset<T, LicenseCacheUpdateManyAndReturnArgs<ExtArgs>>,
  ): Prisma.PrismaPromise<
    runtime.Types.Result.GetResult<
      Prisma.$LicenseCachePayload<ExtArgs>,
      T,
      'updateManyAndReturn',
      GlobalOmitOptions
    >
  >;

  /**
   * Create or update one LicenseCache.
   * @param {LicenseCacheUpsertArgs} args - Arguments to update or create a LicenseCache.
   * @example
   * // Update or create a LicenseCache
   * const licenseCache = await prisma.licenseCache.upsert({
   *   create: {
   *     // ... data to create a LicenseCache
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the LicenseCache we want to update
   *   }
   * })
   */
  upsert<T extends LicenseCacheUpsertArgs>(
    args: Prisma.SelectSubset<T, LicenseCacheUpsertArgs<ExtArgs>>,
  ): Prisma.Prisma__LicenseCacheClient<
    runtime.Types.Result.GetResult<
      Prisma.$LicenseCachePayload<ExtArgs>,
      T,
      'upsert',
      GlobalOmitOptions
    >,
    never,
    ExtArgs,
    GlobalOmitOptions
  >;

  /**
   * Count the number of LicenseCaches.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {LicenseCacheCountArgs} args - Arguments to filter LicenseCaches to count.
   * @example
   * // Count the number of LicenseCaches
   * const count = await prisma.licenseCache.count({
   *   where: {
   *     // ... the filter for the LicenseCaches we want to count
   *   }
   * })
   **/
  count<T extends LicenseCacheCountArgs>(
    args?: Prisma.Subset<T, LicenseCacheCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<
            T['select'],
            LicenseCacheCountAggregateOutputType
          >
      : number
  >;

  /**
   * Allows you to perform aggregations operations on a LicenseCache.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {LicenseCacheAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
   **/
  aggregate<T extends LicenseCacheAggregateArgs>(
    args: Prisma.Subset<T, LicenseCacheAggregateArgs>,
  ): Prisma.PrismaPromise<GetLicenseCacheAggregateType<T>>;

  /**
   * Group by LicenseCache.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {LicenseCacheGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   *
   **/
  groupBy<
    T extends LicenseCacheGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: LicenseCacheGroupByArgs['orderBy'] }
      : { orderBy?: LicenseCacheGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<
      Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>
    >,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
      ? `Error: "by" must not be empty.`
      : HavingValid extends Prisma.False
        ? {
            [P in HavingFields]: P extends ByFields
              ? never
              : P extends string
                ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
                : [
                    Error,
                    'Field ',
                    P,
                    ` in "having" needs to be provided in "by"`,
                  ];
          }[HavingFields]
        : 'take' extends Prisma.Keys<T>
          ? 'orderBy' extends Prisma.Keys<T>
            ? ByValid extends Prisma.True
              ? {}
              : {
                  [P in OrderFields]: P extends ByFields
                    ? never
                    : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`;
                }[OrderFields]
            : 'Error: If you provide "take", you also need to provide "orderBy"'
          : 'skip' extends Prisma.Keys<T>
            ? 'orderBy' extends Prisma.Keys<T>
              ? ByValid extends Prisma.True
                ? {}
                : {
                    [P in OrderFields]: P extends ByFields
                      ? never
                      : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`;
                  }[OrderFields]
              : 'Error: If you provide "skip", you also need to provide "orderBy"'
            : ByValid extends Prisma.True
              ? {}
              : {
                  [P in OrderFields]: P extends ByFields
                    ? never
                    : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`;
                }[OrderFields],
  >(
    args: Prisma.SubsetIntersection<T, LicenseCacheGroupByArgs, OrderByArg> &
      InputErrors,
  ): {} extends InputErrors
    ? GetLicenseCacheGroupByPayload<T>
    : Prisma.PrismaPromise<InputErrors>;
  /**
   * Fields of the LicenseCache model
   */
  readonly fields: LicenseCacheFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for LicenseCache.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__LicenseCacheClient<
  T,
  Null = never,
  ExtArgs extends runtime.Types.Extensions.InternalArgs =
    runtime.Types.Extensions.DefaultArgs,
  GlobalOmitOptions = {},
> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: 'PrismaPromise';
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(
    onfulfilled?:
      | ((value: T) => TResult1 | PromiseLike<TResult1>)
      | undefined
      | null,
    onrejected?:
      | ((reason: any) => TResult2 | PromiseLike<TResult2>)
      | undefined
      | null,
  ): runtime.Types.Utils.JsPromise<TResult1 | TResult2>;
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(
    onrejected?:
      | ((reason: any) => TResult | PromiseLike<TResult>)
      | undefined
      | null,
  ): runtime.Types.Utils.JsPromise<T | TResult>;
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(
    onfinally?: (() => void) | undefined | null,
  ): runtime.Types.Utils.JsPromise<T>;
}

/**
 * Fields of the LicenseCache model
 */
export interface LicenseCacheFieldRefs {
  readonly id: Prisma.FieldRef<'LicenseCache', 'String'>;
  readonly payload: Prisma.FieldRef<'LicenseCache', 'Json'>;
  readonly validatedAt: Prisma.FieldRef<'LicenseCache', 'DateTime'>;
  readonly createdAt: Prisma.FieldRef<'LicenseCache', 'DateTime'>;
  readonly updatedAt: Prisma.FieldRef<'LicenseCache', 'DateTime'>;
}

// Custom InputTypes
/**
 * LicenseCache findUnique
 */
export type LicenseCacheFindUniqueArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs =
    runtime.Types.Extensions.DefaultArgs,
> = {
  /**
   * Select specific fields to fetch from the LicenseCache
   */
  select?: Prisma.LicenseCacheSelect<ExtArgs> | null;
  /**
   * Omit specific fields from the LicenseCache
   */
  omit?: Prisma.LicenseCacheOmit<ExtArgs> | null;
  /**
   * Filter, which LicenseCache to fetch.
   */
  where: Prisma.LicenseCacheWhereUniqueInput;
};

/**
 * LicenseCache findUniqueOrThrow
 */
export type LicenseCacheFindUniqueOrThrowArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs =
    runtime.Types.Extensions.DefaultArgs,
> = {
  /**
   * Select specific fields to fetch from the LicenseCache
   */
  select?: Prisma.LicenseCacheSelect<ExtArgs> | null;
  /**
   * Omit specific fields from the LicenseCache
   */
  omit?: Prisma.LicenseCacheOmit<ExtArgs> | null;
  /**
   * Filter, which LicenseCache to fetch.
   */
  where: Prisma.LicenseCacheWhereUniqueInput;
};

/**
 * LicenseCache findFirst
 */
export type LicenseCacheFindFirstArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs =
    runtime.Types.Extensions.DefaultArgs,
> = {
  /**
   * Select specific fields to fetch from the LicenseCache
   */
  select?: Prisma.LicenseCacheSelect<ExtArgs> | null;
  /**
   * Omit specific fields from the LicenseCache
   */
  omit?: Prisma.LicenseCacheOmit<ExtArgs> | null;
  /**
   * Filter, which LicenseCache to fetch.
   */
  where?: Prisma.LicenseCacheWhereInput;
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   *
   * Determine the order of LicenseCaches to fetch.
   */
  orderBy?:
    | Prisma.LicenseCacheOrderByWithRelationInput
    | Prisma.LicenseCacheOrderByWithRelationInput[];
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   *
   * Sets the position for searching for LicenseCaches.
   */
  cursor?: Prisma.LicenseCacheWhereUniqueInput;
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   *
   * Take `±n` LicenseCaches from the position of the cursor.
   */
  take?: number;
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   *
   * Skip the first `n` LicenseCaches.
   */
  skip?: number;
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   *
   * Filter by unique combinations of LicenseCaches.
   */
  distinct?:
    | Prisma.LicenseCacheScalarFieldEnum
    | Prisma.LicenseCacheScalarFieldEnum[];
};

/**
 * LicenseCache findFirstOrThrow
 */
export type LicenseCacheFindFirstOrThrowArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs =
    runtime.Types.Extensions.DefaultArgs,
> = {
  /**
   * Select specific fields to fetch from the LicenseCache
   */
  select?: Prisma.LicenseCacheSelect<ExtArgs> | null;
  /**
   * Omit specific fields from the LicenseCache
   */
  omit?: Prisma.LicenseCacheOmit<ExtArgs> | null;
  /**
   * Filter, which LicenseCache to fetch.
   */
  where?: Prisma.LicenseCacheWhereInput;
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   *
   * Determine the order of LicenseCaches to fetch.
   */
  orderBy?:
    | Prisma.LicenseCacheOrderByWithRelationInput
    | Prisma.LicenseCacheOrderByWithRelationInput[];
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   *
   * Sets the position for searching for LicenseCaches.
   */
  cursor?: Prisma.LicenseCacheWhereUniqueInput;
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   *
   * Take `±n` LicenseCaches from the position of the cursor.
   */
  take?: number;
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   *
   * Skip the first `n` LicenseCaches.
   */
  skip?: number;
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   *
   * Filter by unique combinations of LicenseCaches.
   */
  distinct?:
    | Prisma.LicenseCacheScalarFieldEnum
    | Prisma.LicenseCacheScalarFieldEnum[];
};

/**
 * LicenseCache findMany
 */
export type LicenseCacheFindManyArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs =
    runtime.Types.Extensions.DefaultArgs,
> = {
  /**
   * Select specific fields to fetch from the LicenseCache
   */
  select?: Prisma.LicenseCacheSelect<ExtArgs> | null;
  /**
   * Omit specific fields from the LicenseCache
   */
  omit?: Prisma.LicenseCacheOmit<ExtArgs> | null;
  /**
   * Filter, which LicenseCaches to fetch.
   */
  where?: Prisma.LicenseCacheWhereInput;
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   *
   * Determine the order of LicenseCaches to fetch.
   */
  orderBy?:
    | Prisma.LicenseCacheOrderByWithRelationInput
    | Prisma.LicenseCacheOrderByWithRelationInput[];
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   *
   * Sets the position for listing LicenseCaches.
   */
  cursor?: Prisma.LicenseCacheWhereUniqueInput;
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   *
   * Take `±n` LicenseCaches from the position of the cursor.
   */
  take?: number;
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   *
   * Skip the first `n` LicenseCaches.
   */
  skip?: number;
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   *
   * Filter by unique combinations of LicenseCaches.
   */
  distinct?:
    | Prisma.LicenseCacheScalarFieldEnum
    | Prisma.LicenseCacheScalarFieldEnum[];
};

/**
 * LicenseCache create
 */
export type LicenseCacheCreateArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs =
    runtime.Types.Extensions.DefaultArgs,
> = {
  /**
   * Select specific fields to fetch from the LicenseCache
   */
  select?: Prisma.LicenseCacheSelect<ExtArgs> | null;
  /**
   * Omit specific fields from the LicenseCache
   */
  omit?: Prisma.LicenseCacheOmit<ExtArgs> | null;
  /**
   * The data needed to create a LicenseCache.
   */
  data: Prisma.XOR<
    Prisma.LicenseCacheCreateInput,
    Prisma.LicenseCacheUncheckedCreateInput
  >;
};

/**
 * LicenseCache createMany
 */
export type LicenseCacheCreateManyArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs =
    runtime.Types.Extensions.DefaultArgs,
> = {
  /**
   * The data used to create many LicenseCaches.
   */
  data:
    | Prisma.LicenseCacheCreateManyInput
    | Prisma.LicenseCacheCreateManyInput[];
  skipDuplicates?: boolean;
};

/**
 * LicenseCache createManyAndReturn
 */
export type LicenseCacheCreateManyAndReturnArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs =
    runtime.Types.Extensions.DefaultArgs,
> = {
  /**
   * Select specific fields to fetch from the LicenseCache
   */
  select?: Prisma.LicenseCacheSelectCreateManyAndReturn<ExtArgs> | null;
  /**
   * Omit specific fields from the LicenseCache
   */
  omit?: Prisma.LicenseCacheOmit<ExtArgs> | null;
  /**
   * The data used to create many LicenseCaches.
   */
  data:
    | Prisma.LicenseCacheCreateManyInput
    | Prisma.LicenseCacheCreateManyInput[];
  skipDuplicates?: boolean;
};

/**
 * LicenseCache update
 */
export type LicenseCacheUpdateArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs =
    runtime.Types.Extensions.DefaultArgs,
> = {
  /**
   * Select specific fields to fetch from the LicenseCache
   */
  select?: Prisma.LicenseCacheSelect<ExtArgs> | null;
  /**
   * Omit specific fields from the LicenseCache
   */
  omit?: Prisma.LicenseCacheOmit<ExtArgs> | null;
  /**
   * The data needed to update a LicenseCache.
   */
  data: Prisma.XOR<
    Prisma.LicenseCacheUpdateInput,
    Prisma.LicenseCacheUncheckedUpdateInput
  >;
  /**
   * Choose, which LicenseCache to update.
   */
  where: Prisma.LicenseCacheWhereUniqueInput;
};

/**
 * LicenseCache updateMany
 */
export type LicenseCacheUpdateManyArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs =
    runtime.Types.Extensions.DefaultArgs,
> = {
  /**
   * The data used to update LicenseCaches.
   */
  data: Prisma.XOR<
    Prisma.LicenseCacheUpdateManyMutationInput,
    Prisma.LicenseCacheUncheckedUpdateManyInput
  >;
  /**
   * Filter which LicenseCaches to update
   */
  where?: Prisma.LicenseCacheWhereInput;
  /**
   * Limit how many LicenseCaches to update.
   */
  limit?: number;
};

/**
 * LicenseCache updateManyAndReturn
 */
export type LicenseCacheUpdateManyAndReturnArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs =
    runtime.Types.Extensions.DefaultArgs,
> = {
  /**
   * Select specific fields to fetch from the LicenseCache
   */
  select?: Prisma.LicenseCacheSelectUpdateManyAndReturn<ExtArgs> | null;
  /**
   * Omit specific fields from the LicenseCache
   */
  omit?: Prisma.LicenseCacheOmit<ExtArgs> | null;
  /**
   * The data used to update LicenseCaches.
   */
  data: Prisma.XOR<
    Prisma.LicenseCacheUpdateManyMutationInput,
    Prisma.LicenseCacheUncheckedUpdateManyInput
  >;
  /**
   * Filter which LicenseCaches to update
   */
  where?: Prisma.LicenseCacheWhereInput;
  /**
   * Limit how many LicenseCaches to update.
   */
  limit?: number;
};

/**
 * LicenseCache upsert
 */
export type LicenseCacheUpsertArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs =
    runtime.Types.Extensions.DefaultArgs,
> = {
  /**
   * Select specific fields to fetch from the LicenseCache
   */
  select?: Prisma.LicenseCacheSelect<ExtArgs> | null;
  /**
   * Omit specific fields from the LicenseCache
   */
  omit?: Prisma.LicenseCacheOmit<ExtArgs> | null;
  /**
   * The filter to search for the LicenseCache to update in case it exists.
   */
  where: Prisma.LicenseCacheWhereUniqueInput;
  /**
   * In case the LicenseCache found by the `where` argument doesn't exist, create a new LicenseCache with this data.
   */
  create: Prisma.XOR<
    Prisma.LicenseCacheCreateInput,
    Prisma.LicenseCacheUncheckedCreateInput
  >;
  /**
   * In case the LicenseCache was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<
    Prisma.LicenseCacheUpdateInput,
    Prisma.LicenseCacheUncheckedUpdateInput
  >;
};

/**
 * LicenseCache delete
 */
export type LicenseCacheDeleteArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs =
    runtime.Types.Extensions.DefaultArgs,
> = {
  /**
   * Select specific fields to fetch from the LicenseCache
   */
  select?: Prisma.LicenseCacheSelect<ExtArgs> | null;
  /**
   * Omit specific fields from the LicenseCache
   */
  omit?: Prisma.LicenseCacheOmit<ExtArgs> | null;
  /**
   * Filter which LicenseCache to delete.
   */
  where: Prisma.LicenseCacheWhereUniqueInput;
};

/**
 * LicenseCache deleteMany
 */
export type LicenseCacheDeleteManyArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs =
    runtime.Types.Extensions.DefaultArgs,
> = {
  /**
   * Filter which LicenseCaches to delete
   */
  where?: Prisma.LicenseCacheWhereInput;
  /**
   * Limit how many LicenseCaches to delete.
   */
  limit?: number;
};

/**
 * LicenseCache without action
 */
export type LicenseCacheDefaultArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs =
    runtime.Types.Extensions.DefaultArgs,
> = {
  /**
   * Select specific fields to fetch from the LicenseCache
   */
  select?: Prisma.LicenseCacheSelect<ExtArgs> | null;
  /**
   * Omit specific fields from the LicenseCache
   */
  omit?: Prisma.LicenseCacheOmit<ExtArgs> | null;
};
